format:

	python -m json.tool normal.json > test.json
	python -m json.tool test.json > normal.json
	python -m json.tool landmark.json > test.json
	python -m json.tool test.json > landmark.json
	rm test.json
